[functions]
verify_jwt = true

[functions.v1-crawl]
verify_jwt = false

[functions.openapi]
verify_jwt = false

[functions.apikeys-generate]
verify_jwt = true

[functions.apikeys-revoke]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true
