
[functions]
verify_jwt = true

[functions.v1-crawl]
verify_jwt = false

[functions.openapi]
verify_jwt = false

[functions.apikeys-generate]
verify_jwt = true

[functions.apikeys-revoke]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

# Google OAuth flow
[functions.google-oauth-start]
verify_jwt = true

[functions.google-status]
verify_jwt = true

[functions.google-disconnect]
verify_jwt = true

[functions.google-oauth-callback]
verify_jwt = false

# Dropbox OAuth flow
[functions.dropbox-oauth-start]
verify_jwt = true

[functions.dropbox-status]
verify_jwt = true

[functions.dropbox-disconnect]
verify_jwt = true

[functions.dropbox-oauth-callback]
verify_jwt = false
